### ISSUE TITLE
securly pass igving CSRF token mismatch after trying to sign in how do i fix this 

### ISSUE THREAD

**Issue by cheemzburgs** [AshtonDavies/LTMEAT#2]
PLEASE HELP

**Comment by AshtonDavies** [comment]
What is the Securly token mismatch you are having trouble with?

**Comment by cheemzburgs** [comment]
securlypass, e-hallpass was bought by securly
________________________________

**Comment by AshtonDavies** [comment]
I don't know what Securly's custom sign-in method has to do with this repository. Maybe sign in with Google or as an existing user or contact your school to fix this issue.

**Comment by cheemzburgs** [comment]
ok, i talked with my TST and he said the new securly update basically broke everything that branches off of securly
________________________________

**Comment by cheemzburgs** [comment]
our whole school cant use seculrypass   <https://emojipedia.org/skull>
💀
________________________________
