### ISSUE TITLE
How did you make the links?

### ISSUE THREAD

**Issue by Mazedotexe** [AshtonDavies/LTMEAT#4]
I am curious as to how all of these links were made because they cannot be opened through normal links or commands. But I can drag to new tab or even just middle-click to open them. How was this made? How could I do this too?

**Comment by AshtonDavies** [comment]
The links are chrome://hang and chrome://kill, plus the extension generated background pages. Each has an onclick attribute to the a tag with "return false;" to make people drag them instead so it works properly.

**Comment by Mazedotexe** [comment]
> The links are chrome://hang and chrome://kill, plus the extension generated background pages. Each has an onclick attribute to the a tag with "return false;" to make people drag them instead so it works properly.

Oh, I didn't realize it was that simple lol
Thanks :)
